export const menus = [
  {
    menu_aid: 1,
    menu_title: "2pcs Chicken Joy",
    menu_category: "Chicken Joy",
    menu_price: "200",
    menu_img: "chicken-1.webp",
  },
  {
    menu_aid: 2,
    menu_title: "3pcs Chicken Joy",
    menu_category: "Chicken Joy",
    menu_price: "270",
    menu_img: "chicken-2.webp",
  },
  {
    menu_aid: 3,
    menu_title: "6pcs Chicken Bucket w/ 2pcs Fries",
    menu_category: "Chicken Joy",
    menu_price: "470",
    menu_img: "chicken-3.webp",
  },
  {
    menu_aid: 4,
    menu_title: "6pcs Chicken Bucket w/ Sphagetti Family Pan",
    menu_category: "Chicken Joy",
    menu_price: "770",
    menu_img: "chicken-4.webp",
  },
  {
    menu_aid: 5,
    menu_title: "6pcs Chicken Bucket w/ Fries",
    menu_category: "Chicken Joy",
    menu_price: "370",
    menu_img: "chicken-5.webp",
  },
  {
    menu_aid: 6,
    menu_title: "6pcs Chicken Bucket",
    menu_category: "Chicken Joy",
    menu_price: "400",
    menu_img: "chicken-6.webp",
  },
  {
    menu_aid: 7,
    menu_title: "Value Meal",
    menu_category: "Value Meal",
    menu_price: "270",
    menu_img: "value-meal-1.webp",
  },
  {
    menu_aid: 8,
    menu_title: "3pcs Chicken Sandwich",
    menu_category: "Value Meal",
    menu_price: "270",
    menu_img: "value-meal-2.webp",
  },
  {
    menu_aid: 27,
    menu_title: "2pcs Chickenjoy Burger Steak w/ Peach Mango Pie",
    menu_category: "Value Meal",
    menu_price: "270",
    menu_img: "value-meal-3.webp",
  },
  {
    menu_aid: 28,
    menu_title: "8pcs Chickenjoy Bucket w/ Peach Mango Pie",
    menu_category: "Value Meal",
    menu_price: "270",
    menu_img: "value-meal-4.webp",
  },
  {
    menu_aid: 29,
    menu_title: "2pcs Chicken Sandwich w/ Fries",
    menu_category: "Value Meal",
    menu_price: "270",
    menu_img: "value-meal-5.webp",
  },
  {
    menu_aid: 9,
    menu_title: "Regular Yumburger",
    menu_category: "Burger",
    menu_price: "69",
    menu_img: "burger-1.webp",
  },
  {
    menu_aid: 10,
    menu_title: "Regular Yumburger w/ Fries",
    menu_category: "Burger",
    menu_price: "100",
    menu_img: "burger-2.webp",
  },
  {
    menu_aid: 22,
    menu_title: "Cheesy Yumburger",
    menu_category: "Burger",
    menu_price: "80",
    menu_img: "burger-3.webp",
  },
  {
    menu_aid: 23,
    menu_title: "Cheesy Yumburger w/ Fries",
    menu_category: "Burger",
    menu_price: "110",
    menu_img: "burger-4.webp",
  },
  {
    menu_aid: 24,
    menu_title: "Champ Jr.",
    menu_category: "Burger",
    menu_price: "140",
    menu_img: "burger-5.webp",
  },
  {
    menu_aid: 25,
    menu_title: "Champ Jr. w/ Fries",
    menu_category: "Burger",
    menu_price: "160",
    menu_img: "burger-6.webp",
  },
  {
    menu_aid: 26,
    menu_title: "Champ",
    menu_category: "Burger",
    menu_price: "180",
    menu_img: "burger-7.webp",
  },
  {
    menu_aid: 27,
    menu_title: "Champ w/ Fries",
    menu_category: "Burger",
    menu_price: "180",
    menu_img: "burger-8.webp",
  },
  {
    menu_aid: 11,
    menu_title: "Mango Pie",
    menu_category: "Desserts",
    menu_price: "69",
    menu_img: "dessert-1.webp",
  },
  {
    menu_aid: 12,
    menu_title: "Ube Pie",
    menu_category: "Desserts",
    menu_price: "69",
    menu_img: "dessert-2.webp",
  },
  {
    menu_aid: 13,
    menu_title: "Peach Mango Pie",
    menu_category: "Desserts",
    menu_price: "69",
    menu_img: "dessert-3.webp",
  },
  {
    menu_aid: 34,
    menu_title: "Pineapple Juice",
    menu_category: "Desserts",
    menu_price: "69",
    menu_img: "dessert-4.webp",
  },
  {
    menu_aid: 35,
    menu_title: "Pepsi Juice",
    menu_category: "Desserts",
    menu_price: "69",
    menu_img: "dessert-4.webp",
  },
  {
    menu_aid: 14,
    menu_title: "Palabok",
    menu_category: "Palabok",
    menu_price: "200",
    menu_img: "palabok-1.webp",
  },
  {
    menu_aid: 15,
    menu_title: "Palabok w/ Drinks",
    menu_category: "Palabok",
    menu_price: "220",
    menu_img: "palabok-2.webp",
  },
  {
    menu_aid: 35,
    menu_title: "Palabok Family Pan",
    menu_category: "Palabok",
    menu_price: "320",
    menu_img: "palabok-3.webp",
  },
  {
    menu_aid: 36,
    menu_title: "Palabok Family Pan 8pcs Chicken Bucket w/ Peach Mango Pie",
    menu_category: "Palabok",
    menu_price: "550",
    menu_img: "palabok-3.webp",
  },
  {
    menu_aid: 16,
    menu_title: "Jolly Spaghetti",
    menu_category: "Spaghetti",
    menu_price: "98",
    menu_img: "spag-1.webp",
  },
  {
    menu_aid: 17,
    menu_title: "Jolly Spaghetti w/ Chickenjoy",
    menu_category: "Spaghetti",
    menu_price: "120",
    menu_img: "spag-2.webp",
  },
  {
    menu_aid: 37,
    menu_title: "Jolly Spaghetti Family Pan",
    menu_category: "Spaghetti",
    menu_price: "410",
    menu_img: "spag-3.webp",
  },
  {
    menu_aid: 18,
    menu_title: "Burger Steak",
    menu_category: "Burger Steak",
    menu_price: "75",
    menu_img: "steak-1.webp",
  },
  {
    menu_aid: 19,
    menu_title: "6pcs Burger Steak",
    menu_category: "Burger Steak",
    menu_price: "240",
    menu_img: "steak-2.webp",
  },
  {
    menu_aid: 30,
    menu_title: "6pcs Burger Steak 6pcs Chicken Bucket w/ Peach Mango Pie",
    menu_category: "Burger Steak",
    menu_price: "240",
    menu_img: "steak-3.webp",
  },
  {
    menu_aid: 20,
    menu_title: "Regular Fries",
    menu_category: "Sides",
    menu_price: "45",
    menu_img: "sides-1.webp",
  },
  {
    menu_aid: 21,
    menu_title: "Mashed Potato",
    menu_category: "Sides",
    menu_price: "55",
    menu_img: "sides-2.webp",
  },
  {
    menu_aid: 31,
    menu_title: "White Rice",
    menu_category: "Sides",
    menu_price: "30",
    menu_img: "sides-3.webp",
  },
  {
    menu_aid: 32,
    menu_title: "Adobo Rice",
    menu_category: "Sides",
    menu_price: "50",
    menu_img: "sides-4.webp",
  },
  {
    menu_aid: 33,
    menu_title: "Small Jolly Spaghetti",
    menu_category: "Sides",
    menu_price: "70",
    menu_img: "sides-5.webp",
  },
];
